// <auto-generated />
namespace Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class classroom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(classroom));
        
        string IMigrationMetadata.Id
        {
            get { return "202108081114235_classroom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
